namespace UnicontaISO20022CreditTransfer
{
    public enum SEPACountries
    {
        AT = 1,
        BE = 2,
        BG = 3,
        HR = 4,
        CY = 5,
        CZ = 6,
        DK = 7,
        EE = 8,
        FI = 9,
        FR = 10,
        DE = 11,
        GI = 12,
        GR = 13,
        HU = 14,
        IS = 15,
        IE = 16,
        IT = 17,
        LV = 18,
        LI = 19,
        LT = 20,
        LU = 21,
        MT = 22,
        MC = 23,
        NL = 24,
        NO = 25,
        PL = 26,
        PT = 27,
        RO = 28,
        SM = 29,
        SK = 30,
        SI = 31,
        ES = 32,
        SE = 33,
        CH = 34
    }
}
